- name: Lookup user ID
  ansible.builtin.uri:
    url: '{{ pmm_server_uri }}{{ pmm_grafana_api }}/users/lookup?loginOrEmail={{ item.login }}'
    method: GET
    force_basic_auth: true
    validate_certs: '{{ pmm_server_insecure }}'
    body_format: json
    url_password: '{{ pmm_api_credentials[1] }}'
    url_username: '{{ pmm_api_credentials[0] }}'
  register: pmm_check_user_id

- name: Grant Grafana Admin permissions
  ansible.builtin.uri:
    url: '{{ pmm_server_uri }}{{ pmm_grafana_api_users }}/{{ pmm_check_user_id.json.id }}/permissions'
    method: PUT
    force_basic_auth: yes
    validate_certs: '{{ pmm_server_insecure }}'
    body_format: json
    body:
      isGrafanaAdmin: True
    url_password: '{{ pmm_api_credentials[1] }}'
    url_username: '{{ pmm_api_credentials[0] }}'
  when: not pmm_check_user_id.json.isGrafanaAdmin | default(False) | bool
