---
preflight_distro_versions:
  centos:
    - 7
    - 8
    - 9
  oraclelinux:
    - 8
  redhat:
    - 7
    - 8
  debian:
    - 11
  ubuntu:
    - 22
preflight_distros: '{{ preflight_distro_versions | list }}'
...
