- name: Current Alert Template
  ansible.builtin.debug:
   msg: "{{ pmm_template_item.name }}"

- name: Set pmm_alerting_template_body
  ansible.builtin.set_fact:
    pmm_alerting_template_body: "{{ new_item|default({}) | combine({ 'templates': [pmm_template_item] }) | to_yaml(indent=2) }}"

- name: Create alert templates
  ansible.builtin.uri:
    url: '{{ pmm_server_uri }}{{ pmm_api_alerting_templates_create }}'
    method: POST
    user: '{{ pmm_api_credentials[0] }}'
    password: '{{ pmm_api_credentials[1] }}'
    body: {"yaml": "{{ pmm_alerting_template_body }}"}
    force_basic_auth: yes
    status_code:
      - 200
      - 409
    body_format: json
    validate_certs: '{{ pmm_server_insecure }}'
  when: (pmm_template_item.name is defined and pmm_template_item.name not in pmm_existing_alert_templates)

- name: Update alert templates
  ansible.builtin.uri:
    url: '{{ pmm_server_uri }}{{ pmm_api_alerting_templates_update }}'
    method: POST
    user: '{{ pmm_api_credentials[0] }}'
    password: '{{ pmm_api_credentials[1] }}'
    body:
      {
      "name": "{{ pmm_template_item.name }}",
      "yaml": "{{ pmm_alerting_template_body }}"
      }
    force_basic_auth: yes
    status_code:
      - 200
      - 409
    body_format: json
    validate_certs: '{{ pmm_server_insecure }}'
  when: (pmm_template_item.name is defined and pmm_template_item.name in pmm_existing_alert_templates)
