---
- name: Install extra tools
  ansible.builtin.package:
    name: "{{ tools_packages }}"
    state: present
  become: yes
  tags:
    - sudo

- name: Add percona gpg rpm key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ tools_percona_gpg_key_url }}"
  become: yes
  tags:
    - sudo

- name: Install percona-release package
  ansible.builtin.package:
    name: "{{ tools_percona_release_url }}"
    state: present
  become: yes
  tags:
    - sudo

- name: enable percona toolkit repo
  ansible.builtin.command: "percona-release enable {{ tools_percona_toolkit_repo }}"
  become: yes
  tags:
    - sudo

- name: Install percona toolkit
  ansible.builtin.package:
    name: percona-toolkit
    state: present
  become: yes
  tags:
    - sudo

...
